# fly.toml app configuration file generated for frameworkers-twilight-river-6013 on 2024-12-28T22:59:57+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frameworkers-twilight-river-6013'
primary_region = 'nrt'

[build]
  dockerfile = './Dockerfile.dev'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
